# Generated by Django 5.2 on 2025-04-13 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paws_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reminder',
            options={},
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='description',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='family',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='is_recurring',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='pet',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='recurrence_type',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='recurrence_value',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='title',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='user',
        ),
        migrations.AddField(
            model_name='reminder',
            name='completed_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='paws_api.post'),
        ),
        migrations.AddField(
            model_name='reminder',
            name='last_completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='next_due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('COMPLETED', 'Completado'), ('OVERDUE', 'Vencido')], default='PENDING', max_length=10),
        ),
    ]
