# Generated by Django 5.1.6 on 2025-04-12 22:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paws_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reminder',
            options={'ordering': ['due_date']},
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='reminder_type',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='status',
        ),
        migrations.AddField(
            model_name='reminder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reminder',
            name='family_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_reminders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reminder',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reminder',
            name='recurrence_type',
            field=models.CharField(choices=[('NONE', 'No repetir'), ('DAILY', 'Diario'), ('WEEKLY', 'Semanal'), ('MONTHLY', 'Mensual')], default='NONE', max_length=10),
        ),
        migrations.AddField(
            model_name='reminder',
            name='recurrence_value',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='reminder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='due_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='pet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='paws_api.pet'),
        ),
    ]
