# Generated by Django 5.1.6 on 2025-04-12 22:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paws_api', '0002_alter_reminder_options_remove_reminder_reminder_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reminder',
            old_name='family_member',
            new_name='assigned_to',
        ),
        migrations.AlterField(
            model_name='reminder',
            name='pet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='paws_api.pet'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_reminders', to=settings.AUTH_USER_MODEL),
        ),
    ]
