# Generated by Django 5.2 on 2025-04-14 00:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paws_api', '0002_alter_reminder_options_remove_reminder_assigned_to_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reminder',
            options={'ordering': ['due_date']},
        ),
        migrations.AddField(
            model_name='reminder',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_reminders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reminder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='due_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='family_reminders', to='paws_api.family'),
        ),
        migrations.AddField(
            model_name='reminder',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reminder',
            name='pet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='paws_api.pet'),
        ),
        migrations.AddField(
            model_name='reminder',
            name='recurrence_type',
            field=models.CharField(choices=[('NONE', 'No repetir'), ('DAILY', 'Diario'), ('WEEKLY', 'Semanal'), ('MONTHLY', 'Mensual')], default='NONE', max_length=10),
        ),
        migrations.AddField(
            model_name='reminder',
            name='recurrence_value',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='reminder',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_reminders', to=settings.AUTH_USER_MODEL),
        ),
    ]
