# Generated by Django 5.1.7 on 2025-04-03 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paws_api', '0002_alter_user_first_name_alter_user_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='codeFam',
            field=models.CharField(default='No Code', max_length=10),
        ),
    ]
