# Generated by Django 5.1.6 on 2025-04-13 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paws_api', '0003_rename_family_member_reminder_assigned_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='family_reminders', to='paws_api.family'),
        ),
    ]
