# Generated by Django 5.2 on 2025-04-14 04:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paws_api', '0003_alter_reminder_options_reminder_assigned_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_reminders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reminder',
            name='completion_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
