# Generated by Django 5.1.7 on 2025-04-03 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paws_api', '0004_pet_vaccines_alter_pet_adoption_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
