# Generated by Django 5.1.7 on 2025-04-03 07:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paws_api', '0005_delete_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 3, 7, 2, 45, 682318, tzinfo=datetime.timezone.utc)),
        ),
    ]
