# Generated by Django 5.1.6 on 2025-04-05 20:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paws_api', '0006_alter_reminder_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='pet_type',
            field=models.CharField(choices=[('DOG', 'Perro'), ('CAT', 'Gato'), ('BIRD', 'Ave'), ('FISH', 'Pez'), ('RODENT', 'Roedor'), ('REPTILE', 'Reptil'), ('OTHER', 'Otro')], max_length=10),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 5, 20, 4, 28, 456176, tzinfo=datetime.timezone.utc)),
        ),
    ]
