# Generated by Django 5.1.6 on 2025-04-05 21:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paws_api', '0007_alter_pet_pet_type_alter_reminder_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='pets/photos/'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='vaccines',
            field=models.FileField(blank=True, null=True, upload_to='pets/vaccines/'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 5, 21, 58, 59, 904501, tzinfo=datetime.timezone.utc)),
        ),
    ]
