# Generated by Django 5.1.6 on 2025-04-05 22:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paws_api', '0008_alter_pet_photo_alter_pet_vaccines_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 5, 22, 20, 43, 637118, tzinfo=datetime.timezone.utc)),
        ),
    ]
