# Generated by Django 5.1.6 on 2025-04-05 22:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paws_api', '0011_alter_reminder_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 5, 22, 45, 33, 158493, tzinfo=datetime.timezone.utc)),
        ),
    ]
