# Generated by Django 5.1.6 on 2025-04-06 18:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paws_api', '0012_alter_reminder_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postimage',
            name='image_type',
        ),
        migrations.RemoveField(
            model_name='postimage',
            name='url',
        ),
        migrations.AddField(
            model_name='post',
            name='pet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='paws_api.pet'),
        ),
        migrations.AddField(
            model_name='postimage',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postimage',
            name='caption',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postimage',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='paws_api.family'),
        ),
        migrations.AddField(
            model_name='postimage',
            name='pet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='paws_api.pet'),
        ),
        migrations.AddField(
            model_name='postimage',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='posts/photos/'),
        ),
        migrations.AddField(
            model_name='postimage',
            name='visibility',
            field=models.CharField(choices=[('PERSONAL', 'Personal'), ('FAMILY', 'Familia')], default='FAMILY', max_length=10),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='paws_api.post'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='due_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
