# Generated by Django 5.1.6 on 2025-04-06 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paws_api', '0013_remove_postimage_image_type_remove_postimage_url_and_more'),
    ]

    operations = [
    ]
